### ISSUE TITLE
Windows下预处理的时候出现了错误

### ISSUE THREAD

**Issue by hello-lx** [zhulf0804/PointPillars#1]
我是3D目标检测的新手，看了你的博客后感觉受益匪浅，也想实践一下3D目标检测，但是遇到了一些问题。安装环境的时候并未发现任何异常，ops也成功安装了，但是开起预处理程序的时候出现了错误，能帮忙看看吗？非常感谢

PS E:\XSpace\DeepLearning\PointPillars> python pre_process_kitti.py --data_root D:\BaiduNetdiskDownload\object
Processing train data..
  0%|                                                                                                                                                         | 0/3712 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "pre_process_kitti.py", line 159, in <module>
    main(args)
  File "pre_process_kitti.py", line 137, in main
    kitti_train_infos_dict = create_data_info_pkl(data_root, 'train', prefix, db=True)
  File "pre_process_kitti.py", line 72, in create_data_info_pkl
    image_shape=image_shape)
  File "E:\XSpace\DeepLearning\PointPillars\utils\process.py", line 695, in remove_outside_points
    indices = points_in_bboxes(points[:, :3], frustum_surfaces)  # (N, 1)
TypeError: expected dtype object, got 'numpy.dtype[bool_]'

**Comment by zhulf0804** [comment]
Hello, 

This error is possibly due to an incompatibility between your `numpy` and `numba` version.

Please try upgrading your `numba` to the latest version ?

Best regards.

**Comment by hello-lx** [comment]
谢谢，已经解决了
