### ISSUE TITLE
ImportError: DLL load failed while importing voxel_op: The paging file is too small for this operation to complete.

### ISSUE THREAD

**Issue by ianphoi** [zhulf0804/PointPillars#10]
(SimplePointPillar) C:\Users\ianph\SimplePointPillar>python train.py --data_root your_path_to_kitti
==================== 0 ====================
  0%|                                                                          | 0/619 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ianph\SimplePointPillar\train.py", line 7, in <module>
    from utils import setup_seed
  File "C:\Users\ianph\SimplePointPillar\utils\__init__.py", line 3, in <module>
    from .process import bbox_camera2lidar, bbox3d2bevcorners, box_collision_test, \
  File "C:\Users\ianph\SimplePointPillar\utils\process.py", line 7, in <module>
    from ops.iou3d_module import boxes_overlap_bev, boxes_iou_bev
  File "C:\Users\ianph\SimplePointPillar\ops\__init__.py", line 1, in <module>
    from .voxel_module import Voxelization
  File "C:\Users\ianph\SimplePointPillar\ops\voxel_module.py", line 5, in <module>
    from .voxel_op import hard_voxelize
ImportError: DLL load failed while importing voxel_op: The paging file is too small for this operation to complete.

**Comment by zhulf0804** [comment]
Hello, I also find the same error in https://github.com/Spandan-Madan/Pytorch_fine_tuning_Tutorial/issues/10#issuecomment-499406167.

Try reducing the number of workers in DataLoader by setting `--num_workers 1` ?

**Comment by ianphoi** [comment]
i change the num worker = 0, and the problem is solved, but now a new problem arise

**Comment by ianphoi** [comment]
(SimplePointPillar) C:\Users\ianph\SimplePointPillar>python train.py --data_root your_path_to_kitti
==================== 0 ====================
  0%|                                                                                                                                                                                 | 0/619 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main(args)
  File "train.py", line 68, in main
    for i, data_dict in enumerate(tqdm(train_dataloader)):
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\site-packages\torch\utils\data\dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\ianph\anaconda3\envs\SimplePointPillar\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\ianph\SimplePointPillar\dataset\kitti.py", line 104, in __getitem__
    pts = read_points(pts_path)
  File "C:\Users\ianph\SimplePointPillar\utils\io.py", line 22, in read_points
    return np.fromfile(file_path, dtype=np.float32).reshape(-1, dim)
FileNotFoundError: [Errno 2] No such file or directory: 'your_path_to_kitti\\your_path_to_kitti\\training\\velodyne_reduced\\004037.bin'

**Comment by ianphoi** [comment]
the file is located at your_path_to_kitti\training\velodyne_reduced\004037.bin'
and not //FileNotFoundError: [Errno 2] No such file or directory: 'your_path_to_kitti\your_path_to_kitti\training\velodyne_reduced\004037.bin'//

**Comment by ianphoi** [comment]
![path](https://user-images.githubusercontent.com/111128654/184620153-f0d7cf26-9c81-4701-947f-d324272337f2.png)

**Comment by zhulf0804** [comment]
Maybe there are some path problems when you pre-process KITTI dataset.

Now, you can try `python train.py --data_root ./` if your KITTI dataset is under `your_path_to_kitti` or `./your_path_to_kitti`, as you mentioned above.

**Comment by ianphoi** [comment]
(SimplePointPillar) C:\Users\ianph\SimplePointPillar>python train.py --data_root ./
Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main(args)
  File "train.py", line 25, in main
    train_dataset = Kitti(data_root=args.data_root,
  File "C:\Users\ianph\SimplePointPillar\dataset\kitti.py", line 49, in __init__
    self.data_infos = read_pickle(os.path.join(data_root, f'kitti_infos_{split}.pkl'))
  File "C:\Users\ianph\SimplePointPillar\utils\io.py", line 8, in read_pickle
    with open(file_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './kitti_infos_train.pkl'

(SimplePointPillar) C:\Users\ianph\SimplePointPillar>

**Comment by ianphoi** [comment]
i tried to add ./ into the pkl file but the it does not allow special character

**Comment by ianphoi** [comment]
nvm, i just rename my file as data and change my --data root data and solve this issue

**Comment by ianphoi** [comment]
![3](https://user-images.githubusercontent.com/111128654/184685542-4deabbfd-dafc-4a7a-a98c-490c620a40a2.png)

**Comment by ianphoi** [comment]
Do you think i need to redownload the file since FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0. which may cause FileNotFoundError: [Errno 2] No such file or directory: 'data\\data\\training\\velodyne_reduced\\004037.bin
![3](https://user-images.githubusercontent.com/111128654/184685801-c43ab0c7-168d-4a56-a20d-565fda074880.png)
'

**Comment by ianphoi** [comment]
Still have the same error
FileNotFoundError: [Errno 2] No such file or directory: 'data\\data\\training\\velodyne_reduced\\004037.bin'

**Comment by ianphoi** [comment]
I found out that in \utils\io.py, in line 23, the file_path is data\data\training\velodyne_reduced\004037.bin

**Comment by zhulf0804** [comment]
> I found out that in \utils\io.py, in line 23, the file_path is data\data\training\velodyne_reduced\004037.bin

It's strange about  your repetitive data path `data\data` and `your_path_to_kitti\your_path_to_kitti`. 

Did you pre-process KITTI by `python pre_process_kitti.py --data_root your_path_to_kitti`, where `your_path_to_kitti` is the absolute path to KITTI. 

`your_path_to_kitti` is the style of `/mnt/ssd1/lifa_rdata/det/kitti`, and the contents included in `/mnt/ssd1/lifa_rdata/det/kitti` can be seen [Datasets](https://github.com/zhulf0804/PointPillars#datasets).

**Comment by ianphoi** [comment]
![4](https://user-images.githubusercontent.com/111128654/184802911-b2999439-fdc1-4c5a-995f-42680617d594.png)
I think so, I run the code on anaconda terminal
activate SimplePointPillar
cd SimplePointPillar
cd ops
python setup.py develop
cd..
python pre_process_kitti.py --data_root data
python train.py --data_root data
python evaluate.py --ckpt pretrained/epoch_160.pth --data_root data

**Comment by Hongsehyun** [comment]
now I have same issue... about  data path like `FileNotFoundError: [Errno 2] No such file or directory: 'kitti\\kitti\\training\\velodyne_reduced\\004037.bin'`

when i ran this code : `python train.py --data_root kitti`

and it's strange... if i ran this code : `python train.py --data_root kitti/`

this error was presented

`FileNotFoundError: [Errno 2] No such file or directory: 'kitti/kitti\\training\\velodyne_reduced\\004037.bin'`

I composed the Kitti data path just like this 
![image](https://user-images.githubusercontent.com/84533279/184863963-fadd4894-6755-41b6-9cac-90e5a3ab8761.png)

Did anyone solve it? thanks in advance...

**Comment by zhulf0804** [comment]
> now I have same issue... about data path like `FileNotFoundError: [Errno 2] No such file or directory: 'kitti\\kitti\\training\\velodyne_reduced\\004037.bin'`
> 
> when i ran this code : `python train.py --data_root kitti`
> 
> and it's strange... if i ran this code : `python train.py --data_root kitti/`
> 
> this error was presented
> 
> `FileNotFoundError: [Errno 2] No such file or directory: 'kitti/kitti\\training\\velodyne_reduced\\004037.bin'`
> 
> I composed the Kitti data path just like this ![image](https://user-images.githubusercontent.com/84533279/184864125-0db22f6f-03ca-49d5-83d2-2ab01f98da4e.png)
> 
> Did anyone solve it? thanks in advance...

Hello, the path problem may be related to OS. I'll check the code using Windows later.

Best.

**Comment by ianphoi** [comment]
> > now I have same issue... about data path like `FileNotFoundError: [Errno 2] No such file or directory: 'kitti\\kitti\\training\\velodyne_reduced\\004037.bin'`
> > when i ran this code : `python train.py --data_root kitti`
> > and it's strange... if i ran this code : `python train.py --data_root kitti/`
> > this error was presented
> > `FileNotFoundError: [Errno 2] No such file or directory: 'kitti/kitti\\training\\velodyne_reduced\\004037.bin'`
> > I composed the Kitti data path just like this ![image](https://user-images.githubusercontent.com/84533279/184864125-0db22f6f-03ca-49d5-83d2-2ab01f98da4e.png)
> > Did anyone solve it? thanks in advance...
> 
> Hello, the path problem may be related to OS. I'll check the code using Windows later.
> 
> Best.

how is the progress??

**Comment by zhulf0804** [comment]
Hi @ianphoi,

Sorry for the late check for I'm busy these days.

I'll check it as soon as possible (maybe tomorrow).

**Comment by zhulf0804** [comment]
Hi @ianphoi,

I find the reason for the above path problem. The path separator `/` and `\` between Linux and Windows are different. The code has only been tested in Linux before. 

So try the following 2 steps:
1. Replace **all** `'/'` with `os.path.sep` in **pre_process_kitti.py**, for example, `'/'.join(lidar_path.split('/')[-3:])` -> `os.path.sep.join(lidar_path.split(os.path.sep)[-3:])`
2. Re-process KITTI dataset with `python pre_process_kitti.py --data_root your_path_to_kitti`

(Windows is not available to me now. If there are any problems about the above steps, please let me know.)

Best.

**Comment by ianphoi** [comment]
Yup, thank you the problem is solved
