### ISSUE TITLE
ModuleNotFoundError: No module named 'ops.voxel_op'

### ISSUE THREAD

**Issue by Hongsehyun** [zhulf0804/PointPillars#11]
Hello, I have this Error... While Running this code'python pre_process_kitti.py --data_root kitti'

my data path is 'kitti' and the error code is here.

File "C:\Users\sehye\anaconda3\envs\pointpillars\lib\site-packages\cumm\tensorview.py", line 20, in <module>
    from cumm.core_cc import tensorview_bind

ModuleNotFoundError: No module named 'ops.voxel_op'

please help me...

**Comment by zhulf0804** [comment]
> Hello, I have this Error... While Running this code'python pre_process_kitti.py --data_root kitti'
> 
> my data path is 'kitti' and the error code is here.
> 
> File "C:\Users\sehye\anaconda3\envs\pointpillars\lib\site-packages\cumm\tensorview.py", line 20, in from cumm.core_cc import tensorview_bind
> 
> ModuleNotFoundError: No module named 'ops.voxel_op'
> 
> please help me...

Hello, please refer to this issue https://github.com/zhulf0804/PointPillars/issues/3#issue-1296701172.

**Comment by Hongsehyun** [comment]
Thanks a lot!

but I have one more problem...! 
It seems to be a problem with the PATH.

My data file configuration is as follows.

```
kitti
    |- training
        |- calib (#7481 .txt)
        |- image_2 (#7481 .png)
        |- label_2 (#7481 .txt)
        |- velodyne (#7481 .bin)
        |- velodyne_reduced (#7481 .bin)
    |- testing
        |- calib (#7518 .txt)
        |- image_2 (#7518 .png)
        |- velodyne (#7518 .bin)
        |- velodyne_reduced (#7518 .bin)
    |- kitti_gt_database (# 19700 .bin)
    |- kitti_infos_train.pkl
    |- kitti_infos_val.pkl
    |- kitti_infos_trainval.pkl
    |- kitti_infos_test.pkl
    |- kitti_dbinfos_train.pkl
```

I configured PATH exactly the same as the PATH presented.

and the code I ran is as follows.
`python train.py --data_root kitti`

but i got this Error code.
![image](https://user-images.githubusercontent.com/84533279/184855219-b8158f9c-b7e1-4aca-b091-e8806faaf6ef.png)


Do you know the solution?
I'm sorry to keep asking. Thank you in advance!

**Comment by zhulf0804** [comment]
Hi, the same problem also occurred in this issue https://github.com/zhulf0804/PointPillars/issues/10#issuecomment-1215456455.

I doubt the path problem may be related to the OS (Ubuntu or Windows). 

I'll check it using Windows OS later.

**Comment by Hongsehyun** [comment]
Ok Thanks! 

I'll also try to proceed with Linux Ubuntu 18.04!

**Comment by zhulf0804** [comment]
Hi @Hongsehyun,

I find the reason for the above path problem. The path separator `/` and `\` between Linux and Windows are different. The code has only been tested in Linux before. 

So try the following 2 steps:
1. Replace **all** `'/'` with `os.path.sep` in **pre_process_kitti.py**, for example, `'/'.join(lidar_path.split('/')[-3:])` -> `os.path.sep.join(lidar_path.split(os.path.sep)[-3:])`
2. Re-process KITTI dataset with `python pre_process_kitti.py --data_root your_path_to_kitti`

(Windows is not available to me now. If there are any problems about the above steps, please let me know.)

Best.

**Comment by Hongsehyun** [comment]
Thank you for the explanation!

I'll try it.
