### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by ianphoi** [zhulf0804/PointPillars#13]
![5](https://user-images.githubusercontent.com/111128654/185363503-4b2c5a86-cce6-4e30-a9b3-a72b6107bdea.png)
so i reduce my batch_size = 3 and num_worker = 1
then i gave me this error
![6](https://user-images.githubusercontent.com/111128654/185363799-d75e948c-e9c8-4a6f-a13b-654797a12551.png)

**Comment by zhulf0804** [comment]
Hello @ianphoi, 

please refer to this issue https://github.com/zhulf0804/PointPillars/issues/2#issuecomment-1155941738.

**Comment by ianphoi** [comment]
thank you, solved it

**Comment by ianphoi** [comment]
How to run the train.py in a GPU?
Since when I was running the train.py with batch size of 1, it take forever and I notice that it runs on my cpu and not gpu

**Comment by zhulf0804** [comment]
It runs on GPU by default.

**Comment by ianphoi** [comment]
how many epoch does I need to train because the program have been running for 20 hours and it is currently at epoch 63. Should i change my num worker and batch size. Currently my num worker =1, batch size = 2

**Comment by ianphoi** [comment]
is it possible to pause the train.py which window can do by pressing control + pause and the change the num worker and batch size then continue to resume the program?

**Comment by zhulf0804** [comment]
Hi @ianphoi,

1. 160 epochs. It takes about 20 hours to train the model (160 epochs) on one RTX 3090 GPU card with the default parameters.
2. Not yet. I'll update the code by supporting model resuming in the future.

Best.

**Comment by ianphoi** [comment]
> Hi @ianphoi,
> 
> 1. 160 epochs. It takes about 20 hours to train the model (160 epochs) on one RTX 3090 GPU card with the default parameters.
> 2. Not yet. I'll update the code by supporting model resuming in the future.
> 
> Best.

alright thank you. You mention that  it uses GPU right. But when I was running the train.py, my task manager indicates zero usage of GPU.
