### ISSUE TITLE
Why overwrite the original coordinates? It seems to be inconsistent with the description of the paper

### ISSUE THREAD

**Issue by xmqv0913** [zhulf0804/PointPillars#14]
https://github.com/zhulf0804/PointPillars/blob/a0e8af7204168a1823d8679cf2379576b4795a27/model/pointpillars.py#L77

**Comment by zhulf0804** [comment]
Thanks for your question.

Please refer to this issue https://github.com/open-mmlab/mmdetection3d/issues/1307 I raised before.

Best regards.

**Comment by xmqv0913** [comment]
Got it, thanks for the reply!
