### ISSUE TITLE
Is reflectivity used in the input?

### ISSUE THREAD

**Issue by cadwallader113** [zhulf0804/PointPillars#15]
Hello zhulf0804.

Is the reflectance of the LiDAR point cloud unused in train?
This is because it seemed that the data after the 3 arrays (x, y, z) of points were not handled.
Will the same result be obtained if the point cloud data .bin with the reflectance set to 0 is given during the test?
@voxelization_cuda.cu
```
hard_voxelize_gpu function
NDim = 3
```
@voxel_module.py
```
voxel_num = hard_voxelize(points, voxels, coors,
num_points_per_voxel, voxel_size,
coors_range, max_points, max_voxels, 3,
  deterministic)
```

**Comment by zhulf0804** [comment]
Hi @cadwallader113,

The reflectance is used. 

`NDim = 3` represents that it processes the 3-dimensional data, but  each data item can be related to its data attribute, such as reflectance. More details please see [here](https://github.com/zhulf0804/PointPillars/blob/main/ops/voxelization/voxelization_cuda.cu).

Best.
