### ISSUE TITLE
有没有适用此项目的 data augmentation 方法？

### ISSUE THREAD

**Issue by KyleYueye** [zhulf0804/PointPillars#23]
适用于 custom 数据集的数据增强方法，比如随机翻转、随机旋转等

**Comment by RunTian1** [comment]
作者的知乎里面有解释，数据增强在这里dataset/data_aug.py

**Comment by RunTian1** [comment]
> 适用于 custom 数据集的数据增强方法，比如随机翻转、随机旋转等

作者的知乎里面有解释，数据增强在这里dataset/data_aug.py
