### ISSUE TITLE
what training algorithms is pointpillar using?

### ISSUE THREAD

**Issue by ianphoi** [zhulf0804/PointPillars#24]
May I ask what type of traning algorithm is PointPillars using? is it Adam or SGD? If it is could you explain it to me?

**Comment by zhulf0804** [comment]
Hello, it's here:

https://github.com/zhulf0804/PointPillars/blob/b9948e73505c8d6bfa631ffdf76c7148e82c5942/train.py#L46-L49

**Comment by ianphoi** [comment]
thank you
