### ISSUE TITLE
Simple Question 

### ISSUE THREAD

**Issue by Coke-das-JHL** [zhulf0804/PointPillars#26]
Hi, Thank you for your work! 

Can you explain in more detail what bbox_dir_cls_pred is among bbox_cls_pred, bbox_pred, and bbox_dir_cls_pred that are the outputs of the Detection Head?

Are there any references?

Thank you.

**Comment by zhulf0804** [comment]
Hi @Coke-das-JHL,

It's box direction (heading, orientation).  Please refer to the [PointPillars](https://openaccess.thecvf.com/content_CVPR_2019/papers/Lang_PointPillars_Fast_Encoders_for_Object_Detection_From_Point_Clouds_CVPR_2019_paper.pdf) paper.
![image](https://user-images.githubusercontent.com/36033208/204120916-19aa1f9f-0396-46b2-b1fb-17b95c724a09.png)

Best.

**Comment by Coke-das-JHL** [comment]
Thank you!
