### ISSUE TITLE
ModuleNotFoundError: No module named 'ops.voxel_op'

### ISSUE THREAD

**Issue by anijyarnon** [zhulf0804/PointPillars#3]
Hi, I tried to run your source code.
But I got an error.
"ModuleNotFoundError: No module named 'ops.voxel_op'"
It seems that it is occurring in the voxel_module.py.
"Import ".voxel_op" could not be resolved"

How can I import ".voxel_op"?
Thank you

**Comment by zhulf0804** [comment]
Hello,
Did you compile the c++/cuda ops as follows:
```
cd ops
python setup.py develop
```

**Comment by anijyarnon** [comment]
Thanks!
I solved it!
