### ISSUE TITLE
关于多类别检测问题

### ISSUE THREAD

**Issue by hehualin-tut** [zhulf0804/PointPillars#37]
首先，感谢您的开源工作，我想问下，如果我自己的数据集李有好多类比如说（摩托车/三轮摩托车），我训练时是不是只需要修改n_class和anchor就可以了，还说我需要预先手工设定anchor，多类别是增加多个类别head还是说需要额外的anchor

**Comment by zhulf0804** [comment]
您好，这个问题可以参考之前的一个[issue](https://github.com/zhulf0804/PointPillars/issues/8)，需要增加对应类别的anchor。
