### ISSUE TITLE
  self.sorted_ids = list(self.data_infos.keys()) AttributeError: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by gdb123** [zhulf0804/PointPillars#40]
你好，在训练过程中出现了如下错误： 请问应该怎么解决呢
  self.sorted_ids = list(self.data_infos.keys())
AttributeError: 'list' object has no attribute 'keys'

**Comment by zhulf0804** [comment]
你好 @gdb123, 错误信息提示self.data_infos是list, 不是字典。数据是通过`pre_process_kitti.py`预处理过的吗？
