### ISSUE TITLE
Batch size under PillarEncoder

### ISSUE THREAD

**Issue by hz3014** [zhulf0804/PointPillars#41]
I found the following line sometimes brings me wrong batch size. eg. I have batch size 8, bs = coors_batch[-1, 0] + 1 should give me value 8, but occasionally gives me value 7.

https://github.com/zhulf0804/PointPillars/blob/b9948e73505c8d6bfa631ffdf76c7148e82c5942/model/pointpillars.py#L94-L97

Just wondering is bs short for batch_size? May I replace it with batch_size value?

**Comment by zhulf0804** [comment]
Hello @hz3014, the first question is "Yes". For the second one, I think you can try.

Best.
