### ISSUE TITLE
requirements依赖包的pointpillars.egg==info查找不到

### ISSUE THREAD

**Issue by lofues** [zhulf0804/PointPillars#45]
pointpillars.egg==info
请问这个包的依赖需要怎么下载

**Comment by abdkhanstd** [comment]
Anny update on this issue ?

**Comment by zhulf0804** [comment]
> Anny update on this issue ?

Hi @abdkhanstd ,

It should be generated by compiling (`python setup.py develop`).

Try removing this line `pointpillars.egg==info` ?

Best.

**Comment by YSAH0714** [comment]
我是删除了的

**Comment by ruiyangyin** [comment]
大飒飒
