### ISSUE TITLE
ModuleNotFoundError:  No module named 'ops.voxel_op'

### ISSUE THREAD

**Issue by farhaniwnl** [zhulf0804/PointPillars#49]
Hello,

I am having an issue when attempting to pre-process the data where I am getting a module not found error with .voxel_op as seen below, also other modules missing (iou3d, .process, etc) from the lines in the screenshot:

![issues](https://github.com/zhulf0804/PointPillars/assets/123670192/e5a85424-9ec4-4180-a0a6-3145f5903a0c)

I would like to say since I saw this in another thread as well, my program does compile and I have visual studio installed. However, I don't have an NVIDIA GPU, and don't know if that is an issue (no CUDA runtime). Below is what it looks like when I compile the program:

![issues2](https://github.com/zhulf0804/PointPillars/assets/123670192/9b6fcfd4-8ad1-4ee1-a42d-0fcdb1e5d6db)

**Comment by zhulf0804** [comment]
Hello, @farhaniwnl.
I'm sorry. I am not familiar with compiling on Windows.
Best.

**Comment by pxxxl** [comment]
Hello, @farhaniwnl.
Have you forgot to compile the program first?
```
cd ops
python setup.py develop
```
