### ISSUE TITLE
Question about mAP calculation

### ISSUE THREAD

**Issue by jonasdieker** [zhulf0804/PointPillars#51]
Hi @zhulf0804, hope you are doing well!

I have read #6 and #12 already, but I still have some questions regarding the evaluation file. I also understand that you are trying to be consistent with mmdet3d, but perhaps you have still have some insights into why specific things were done the way they were:

1. Why are 41 (or less) `score_thresholds` used but only every fourth one is used to calculate the AUC?
2. It seems that the `recalls` are not used at all when computing the AP. Only the `precisions` are summed up and divided by how many values were summed (11, assuming 41 thresholds). Is this why the thresholds are computed first, in order to ensure that the recall steps are even in size?

**Comment by zhulf0804** [comment]
Hello @jonasdieker.
For the first question, I think 11 `score_thresholds` is also ok, but 41 is more precise. More details please refer to [KITTI Det Dataset](https://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d), 
<img width="949" alt="image" src="https://github.com/zhulf0804/PointPillars/assets/36033208/5f8ce91d-8427-4d1b-be2d-5b9cc8cbc059">
For the second question, Yes. And `AP` means average precision under different recalls. 
Best.

**Comment by jonasdieker** [comment]
Great, thank you!
